### ISSUE TITLE
Decomping this or starting from scratch with plain decomp

### ISSUE THREAD

**Issue by CCIGAMES** [CCIGAMES/T04DSTOOL#10]
What are we doing then?!

**Comment by CCIGAMES** [comment]
https://github.com/libsm64/libsm64 here's mario 64 as a lib

**Comment by fgsoftware1** [comment]
> https://github.com/libsm64/libsm64 here's mario 64 as a lib

interface

**Comment by CCIGAMES** [comment]
Yea
