### ISSUE TITLE
Coding issues

### ISSUE THREAD

**Issue by CCIGAMES** [CCIGAMES/T04DSTOOL#11]
Anyone stuck with coding or don't know where to start

**Comment by CCIGAMES** [comment]
basically, we cant edit code without specific tools or decompiling, and it looks like no ones decided whether to decomp our modded rom or starting from scratch with a pre-existing decomp, ive asked but got no response from anyone

**Comment by CCIGAMES** [comment]
https://github.com/CCIGAMES/T04DSTOOL/issues/10 talk about this here, this issue will remain open for other coding issues

**Comment by fgsoftware1** [comment]
> So I
> 
> > > basically, we cant edit code without specific tools or decompiling, and it looks like no ones decided whether to decomp our modded rom or starting from scratch with a pre-existing decomp, ive asked but got no response from anyone
> > 
> > 
> > decompiling only works with original ROMs
> 
> So I guess we'll start from scratch then, but how will we get our custom stuff from our modded rom to a decomp. Xxelevenfangamingxx wouldn't be happy

and how will you compile?

**Comment by CCIGAMES** [comment]
https://n64squid.com/homebrew/n64-sdk/compiling-roms/
